version: '3.9'
services:
  postgres:
    container_name: BACv2.00
    image: postgres
    hostname: localhost
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/BACv2.00/data
    restart: unless-stopped

  pgadmin:
    container_name: BACv2pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/BACv2pgadmin
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:

